events {}

http {
    resolver 127.0.0.11 valid=10s;

    server_names_hash_bucket_size 64;

    server {
        listen 80;
        server_name neuroslop.imbalet.ru;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location / {
            set $upstream http://green_api:8000;
            proxy_pass $upstream;
        }
    }

    server {
        listen 80;
        server_name airflow.neuroslop.imbalet.ru;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location / {
            set $upstream http://green_airflow-webserver:8080;
            proxy_pass $upstream;
        }
    }
}
